return {
  { "ribru17/bamboo.nvim",   name = "bamboo",     lazy = true, priority = 1000 },
  { "catppuccin/nvim",       name = "catppuccin", lazy = true, priority = 1000 },
  { "sainnhe/everforest",    name = "everforest", lazy = true, priority = 1000 },
  { "kepano/flexoki-neovim", name = "flexoki",    lazy = true, priority = 1000 },
  {
    "ellisonleao/gruvbox.nvim",
    name = "gruvbox",
    lazy = true,
    priority = 1000,
    opts = {
      overrides = {
        SignColumn = { link = "Normal" },
      },
    },
  },
  { "sainnhe/gruvbox-material",           name = "gruvbox-material", lazy = true,    priority = 1000 },
  { "rebelot/kanagawa.nvim",              name = "kanagawa",         lazy = true,    priority = 1000 },
  { "tahayvr/matteblack.nvim",            name = "matteblack",       lazy = true,    priority = 1000 },
  { "loctvl842/monokai-pro.nvim",         lazy = true,               priority = 1000 },
  { "EdenEast/nightfox.nvim",             lazy = true,               priority = 1000 },
  { "rose-pine/neovim",                   name = "rose-pine",        lazy = true,    priority = 1000 },
  { "folke/tokyonight.nvim",              name = "tokyonight",       lazy = true,    priority = 1000 },
  { "craftzdog/solarized-osaka.nvim",     name = "solarize",         lazy = true,    priority = 1000 },
  { "st-eez/osaka-jade.nvim",             name = "osaka-jade",       lazy = true,    priority = 1000 },
  { "phha/zenburn.nvim",                  name = "zenburn",          lazy = true,    priority = 1000 },
  { "atelierbram/Base2Tone-nvim",         name = "b2t",              lazy = true,    priority = 1000 },
  { "Mofiqul/dracula.nvim",               name = "dracula",          lazy = true,    priority = 1000 },
  { "xero/miasma.nvim",                   name = "miasma",           lazy = true,    priority = 1000 },
  { "NLKNguyen/papercolor-theme",         name = "papercolor",       lazy = true,    priority = 1000 },
  { "danilo-augusto/vim-afterglow",       name = "afterglow",        lazy = true,    priority = 1000 },
  { "romainl/Apprentice",                 name = "apprentice",       lazy = true,    priority = 1000 },
  { "RRethy/nvim-base16",                 name = "base16",           lazy = true,    priority = 1000 },
  { "plan9-for-vimspace/acme-colors",     name = "acme",             lazy = true,    priority = 1000 },
  { "bjarneo/nes.nvim",                   name = "nes",              lazy = true,    priority = 1000 },
  { "bjarneo/snow.nvim",                  name = "snow",             lazy = true,    priority = 1000 },
  { "steve-lohmeyer/mars.nvim",           name = "mars",             lazy = true,    priority = 1000 },
  { "metalelf0/black-metal-theme-neovim", name = "black-metal",      lazy = false,   priority = 1000 },
  { "e-ink-colorscheme/e-ink.nvim",       name = "e-ink",            lazy = false,   priority = 1000 },
}
